### ISSUE TITLE
Document all Subscriptions events that should be user-raised or user-reacted

### ISSUE THREAD

**Issue by 0joshuaolson1** [Picolab/wiki-issues#9]
EDIT: only publically useful events need to be documented.

**Comment by 0joshuaolson1** [comment]
This includes updating the images in https://picolabs.atlassian.net/wiki/display/docs/Managing+Subscriptions, now hosted in https://github.com/Picolab/pico_lessons/tree/master/assets

**Comment by 0joshuaolson1** [comment]
[Managing+Subscriptions](https://picolabs.atlassian.net/wiki/display/docs/Managing+Subscriptions#ManagingSubscriptions-SubscriptionEvents) is done. Assets are next but low priority.

**Comment by windley** [comment]
Assets?

**Comment by windley** [comment]
Good work on this, BTW.

**Comment by 0joshuaolson1** [comment]
Thanks. Referring to https://github.com/Picolab/pico_lessons/tree/master/assets

**Comment by windley** [comment]
Ah, got it.

**Comment by 0joshuaolson1** [comment]
My OmniGraffle trial expired, so at the moment I'm thinking of leaving the outdated Subscription flowcharts as is instead of recreating them.

**Comment by windley** [comment]
We can buy licenses. Do you want one?

**Comment by 0joshuaolson1** [comment]
Sure. Just for this one thing.

**Comment by 0joshuaolson1** [comment]
Now have one.
